// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgYYyQmTsdhTtd7FZWRyHAiTn9AFn-0Fo',
    appId: '1:777070018091:web:fe4c1dfcaf5d392f6bb46e',
    messagingSenderId: '777070018091',
    projectId: 'authenthicator',
    authDomain: 'authenthicator.firebaseapp.com',
    storageBucket: 'authenthicator.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0LiKf3NLZbi9TCB_bfS98426vSvq1OL8',
    appId: '1:777070018091:android:e45bbcf52e4050a16bb46e',
    messagingSenderId: '777070018091',
    projectId: 'authenthicator',
    storageBucket: 'authenthicator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC2udgUmbU7rUuQnrNYW0UcK6GVV0YGUw',
    appId: '1:777070018091:ios:82eed5f9af4789a76bb46e',
    messagingSenderId: '777070018091',
    projectId: 'authenthicator',
    storageBucket: 'authenthicator.appspot.com',
    iosClientId: '777070018091-dv28k9219suhl9t2a51t66vmtccvp7qo.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC2udgUmbU7rUuQnrNYW0UcK6GVV0YGUw',
    appId: '1:777070018091:ios:82eed5f9af4789a76bb46e',
    messagingSenderId: '777070018091',
    projectId: 'authenthicator',
    storageBucket: 'authenthicator.appspot.com',
    iosClientId: '777070018091-dv28k9219suhl9t2a51t66vmtccvp7qo.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );
}
